[package]
name = "job-submitter"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-config = "1.1.8"
aws-sdk-batch = "1.21.0"
tokio = { version = "1", features = ["full"] }
anyhow = "1.0.82"
clap = { version = "4.5.4", features = ["derive"] }
futures = "0.3.30"
chrono = "0.4.38"

